# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - projects.md
  - resources.md

footer: '&copy; <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" title="Creative Commons Attribution 4.0 License">CC BY 4.0</a> | <a href="/privacy" target="_blank">privacy</a> | <a href="https://www.twitter.com/krisbolton" target="_blank">twitter</a>'

style: light

plugins:
  - jekyll-seo-tag
